name: gateway

services:
  gateway-service:
    build: .
    container_name: gateway-service
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      centinela-net:
        aliases:
          - gateway-service

networks:
  centinela-net:
    external: true
