services:
  gateway-service:
    build: .
    container_name: gateway-service
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "80"
    networks:
      centinela-net:
        aliases:
          - gateway-service

networks:
  centinela-net:
    external: true
